package com.pojo;
// Generated 8 Apr, 2017 1:14:27 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Category generated by hbm2java
 */
public class Category implements java.io.Serializable {

	private Long categoryId;
	private String categoryName;

	public Category() {
	}

	public Category(String categoryName) {
		this.categoryName = categoryName;
	}

	public Long getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

}
