package com.pojo;
// Generated 8 Apr, 2017 1:14:27 PM by Hibernate Tools 5.2.0.Beta1

/**
 * Prodcat generated by hbm2java
 */
public class Prodcat implements java.io.Serializable {

	private Integer proCatId;
	private String prodCatName;

	public Prodcat() {
	}

	public Prodcat(String prodCatName) {
		this.prodCatName = prodCatName;
	}

	public Integer getProCatId() {
		return this.proCatId;
	}

	public void setProCatId(Integer proCatId) {
		this.proCatId = proCatId;
	}

	public String getProdCatName() {
		return this.prodCatName;
	}

	public void setProdCatName(String prodCatName) {
		this.prodCatName = prodCatName;
	}

}
